language: node_js

node_js:
  - 0.6
  - 0.8
  - 0.9

matrix:
  allow_failures:
    - node_js: 0.9

script:
  - secret=`openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in secret`
  - openssl aes-256-cbc -k "$secret" -in config.xml.enc -d -a -out config.xml
  - cat config.xml
